services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "9090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_FEATURES: "docker"
      KC_DB_URL: jdbc:mysql://mysql:3306/sinabro
      KC_DB_USERNAME: sinabro
      KC_DB_PASSWORD: 1234
    command:
      - start-dev
    depends_on:
      - mysql
    networks:
      - authorization_network
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sinabro
      MYSQL_USER: sinabro
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./authorization.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - authorization_network

volumes:
  mysql_data:

networks:
  authorization_network:
    driver: bridge
