services:
  controller-1:
    image: apache/kafka:4.1.0
    container_name: controller-1
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "abcdefghijklmnopqrstuv"
    volumes:
      - controller1_data:/var/lib/kafka/data
    networks:
      - event_network

  controller-2:
    image: apache/kafka:4.1.0
    container_name: controller-2
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "abcdefghijklmnopqrstuv"
    volumes:
      - controller2_data:/var/lib/kafka/data
    networks:
      - event_network

  controller-3:
    image: apache/kafka:4.1.0
    container_name: controller-3
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "abcdefghijklmnopqrstuv"
    volumes:
      - controller3_data:/var/lib/kafka/data
    networks:
      - event_network

  broker-1:
    image: apache/kafka:4.1.0
    container_name: broker-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 4
      # kafka <-> kafka_ui 통신 (INTERNAL), application <-> kafka 통신 (EXTERNAL)
      KAFKA_LISTENERS: INTERNAL://broker-1:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:9093,2@controller-2:9093,3@controller-3:9093"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "abcdefghijklmnopqrstuv"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - controller-1
      - controller-2
      - controller-3
    volumes:
      - broker1_data:/var/lib/kafka/data
    networks:
      - event_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9091:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kraft-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-1:29092
    depends_on:
      - broker-1
    networks:
      - event_network

volumes:
  controller1_data:
  controller2_data:
  controller3_data:
  broker1_data:

networks:
  event_network:
    driver: bridge
